INSERT INTO GENRES (ID, GENRE) VALUES (1, 'romance');
INSERT INTO GENRES (ID, GENRE) VALUES (2, 'action');
INSERT INTO GENRES (ID, GENRE) VALUES (3, 'drama');
INSERT INTO CATEGORIES (ID, CATEGORY) VALUES (1, 'comic');
INSERT INTO CATEGORIES (ID, CATEGORY) VALUES (2, 'manga');
INSERT INTO CATEGORIES (ID, CATEGORY) VALUES (3, 'manhwa');
INSERT INTO COMICS (ID, TITLE, AUTHOR, RELEASE_YEAR) VALUES(1, 'Dragon Ball', 'Akira Toriyama', 1995);
INSERT INTO COMIC_CATEGORY (CATEGORY_ID, COMIC_ID) VALUES (2, 1);
INSERT INTO COMIC_GENRE (GENRE_ID, COMIC_ID) VALUES (2, 1);