INSERT INTO GENRES (ID, GENRE) VALUES (1, 'romance');
INSERT INTO GENRES (ID, GENRE) VALUES (2, 'action');
INSERT INTO GENRES (ID, GENRE) VALUES (3, 'drama');
INSERT INTO CATEGORIES (ID, CATEGORY) VALUES (1, 'comic');
INSERT INTO CATEGORIES (ID, CATEGORY) VALUES (2, 'manga');
INSERT INTO CATEGORIES (ID, CATEGORY) VALUES (3, 'manhwa');